# Definição de variáveis (ambiente “local” do REST Client)
@base_url = https://psychic-disco-7v9xvxr4rgp7frv4v-8080.app.github.dev

### Inserir novo veiculo
POST {{ base_url }}/api/veiculos
Content-Type: application/json

{
  "modelo": "bmw m4 g82",
  "ano": 2024,
  "valor": 1399950.00
}

### Listar todos os veiculos
GET {{ base_url }}/api/veiculos
Accept: application/json

### Buscar veiculos por ID
GET {{ base_url }}/api/veiculos/1
Accept: application/json

### Atualizar veiculo (PUT)
PUT {{ base_url }}/api/veiculos/1
Content-Type: application/json

{
  "modelo": "Supra mk4",
  "ano": 1995,
  "valor": 1200000.00
}

### Remover veiculo (DELETE)
DELETE {{ base_url }}/api/veiculos/1
Accept: */*